# docker-compose.yaml
version: "3"

services:
  api:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: [ "./wait-for-it.sh", "db:5432", "--", "python", "main.py" ]
    volumes:
      - main.log:main.log

  db:
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  main.log:
  data: